// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed crypto4.png
var resourceCrypto4PngData []byte
var resourceCrypto4Png = &fyne.StaticResource{
	StaticName:    "crypto4.png",
	StaticContent: resourceCrypto4PngData,
}

//go:embed batman.png
var resourceBatmanPngData []byte
var resourceBatmanPng = &fyne.StaticResource{
	StaticName:    "batman.png",
	StaticContent: resourceBatmanPngData,
}

//go:embed GNA.png
var resourceGNAPngData []byte
var resourceGNAPng = &fyne.StaticResource{
	StaticName:    "GNA.png",
	StaticContent: resourceGNAPngData,
}
